In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
df=pd.read_csv("diabetes_data_upload.csv")
df

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity     class  
0                No              Yes      Yes     Yes  Positive  
1               Yes               No      Yes      No  Positive  
2                No              Yes      Yes      No  Positive  
3                No               No       No      No  Positive  
4               Yes              Yes      Yes     Yes  Positive  
..              ...              ...      ...     ...       ...  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative  

[520 rows x 17 columns]

In [2]:
data=df.replace({
    'Yes':1,
    'No':0,
    'Positive':1,
    'Negative':0,
    'Male':1,
    'Female':0
})
data

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  1                0                 1         1        1   
1                  0                1                 0         1        0   
2                  1                0                 1         1        0   
3                  1                0                 0         0        0   
4                  1                1                 1         1        1   
..               ...              ...               ...       ...      ...   
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      1  
518      0  
519      0  

[520 rows x 17 columns]

In [3]:
from sklearn .model_selection import train_test_split
X=data.iloc[:,0:16]
y=data.iloc[:,16]

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [5]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,plot_roc_curve

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [7]:
l_reg_model=LogisticRegression(solver='lbfgs', max_iter=400,C=1.5, class_weight='dict', dual=False, penalty='l2', tol=0.0001)
l_reg_model.fit(X_train,y_train)
y_pred=l_reg_model.predict(X_test)
y_pred
acc=accuracy_score(y_test,y_pred)
acc

0.9519230769230769

In [8]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[37  3]
 [ 2 62]]
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        40
           1       0.95      0.97      0.96        64

    accuracy                           0.95       104
   macro avg       0.95      0.95      0.95       104
weighted avg       0.95      0.95      0.95       104



In [9]:
svm_model=svm.SVC(gamma=0.2,C=10.5)#gamma=0.1,C=2)
svm_model.fit(X_train,y_train)
y_pred=svm_model.predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.9807692307692307

In [10]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[38  2]
 [ 0 64]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97        40
           1       0.97      1.00      0.98        64

    accuracy                           0.98       104
   macro avg       0.98      0.97      0.98       104
weighted avg       0.98      0.98      0.98       104



In [11]:
NB_model=GaussianNB(var_smoothing=1.e-04)# BernoulliNB()
y_pred = NB_model.fit(X_train, y_train).predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.9326923076923077

In [12]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[35  5]
 [ 2 62]]
              precision    recall  f1-score   support

           0       0.95      0.88      0.91        40
           1       0.93      0.97      0.95        64

    accuracy                           0.93       104
   macro avg       0.94      0.92      0.93       104
weighted avg       0.93      0.93      0.93       104



In [13]:
DT_model=DecisionTreeClassifier(criterion='entropy', 
                                max_depth=10, 
                                #max_features=None, 
                                #min_samples_leaf=1, 
                                #min_samples_split=2,
                                splitter='random')
y_pred =DT_model.fit(X_train, y_train).predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.9711538461538461

In [14]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[40  0]
 [ 3 61]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        40
           1       1.00      0.95      0.98        64

    accuracy                           0.97       104
   macro avg       0.97      0.98      0.97       104
weighted avg       0.97      0.97      0.97       104



In [15]:
RF_model = RandomForestClassifier(n_estimators=7,max_depth=8,
                                  bootstrap=True, 
                                  criterion='gini',#'entropy',
                                  max_features='sqrt', min_samples_split=2,random_state=42)
y_pred = RF_model.fit(X_train, y_train).predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.9903846153846154

In [16]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[40  0]
 [ 1 63]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        40
           1       1.00      0.98      0.99        64

    accuracy                           0.99       104
   macro avg       0.99      0.99      0.99       104
weighted avg       0.99      0.99      0.99       104



In [20]:
knn_model = KNeighborsClassifier(
    n_neighbors=3, 
    weights='distance',  
    leaf_size=30, 
    p=1, 
    metric='minkowski'
)
y_pred = knn_model.fit(X_train, y_train).predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.9711538461538461

In [21]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[40  0]
 [ 3 61]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        40
           1       1.00      0.95      0.98        64

    accuracy                           0.97       104
   macro avg       0.97      0.98      0.97       104
weighted avg       0.97      0.97      0.97       104



# GridSearchCV

In [22]:
from sklearn.model_selection import GridSearchCV

In [28]:
RF_grid=GridSearchCV(RandomForestClassifier(),{
     "n_estimators":[2,4,6,8,10],
    "max_depth":[2,4,6,8,10,15,20],
    "criterion":['gini','entropy'],
    "max_features":['auto', 'sqrt', 'log2'],
   "bootstrap": [True, False],
    "min_samples_split":[2],
    #"min_sample_leaf":[1,2],
    #'random_state':[1]
},cv=10,verbose=2,n_jobs=4,return_train_score=True)
RF_grid.fit(X, y)
print(RF_grid.best_score_)
print(RF_grid.best_params_)

Fitting 10 folds for each of 420 candidates, totalling 4200 fits
0.9846153846153847
{'bootstrap': False, 'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_split': 2, 'n_estimators': 8}


In [29]:
y_pred=RF_grid.best_estimator_.predict(X)
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

[[200   0]
 [  0 320]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       320

    accuracy                           1.00       520
   macro avg       1.00      1.00      1.00       520
weighted avg       1.00      1.00      1.00       520



In [31]:
svm_grid=GridSearchCV(svm.SVC(),{
    # "C":[0.1,0.4,0.9,1.0,1.5,2.5,5.5,10.5,15.0],
     #"gamma":[0.1,0.2,0.01,0.001,'scale', 'auto'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'gamma': [0.001, 0.01, 0.1, 0.2,1, 10, 100],
    'kernel': ['linear','rbf', 'sigmoid'],
    #'random_state':[0,1,42,None]
},cv=10,verbose=2,n_jobs=4,return_train_score=False)
svm_grid.fit(X, y)
print(svm_grid.best_score_)
print(svm_grid.best_params_)

Fitting 10 folds for each of 126 candidates, totalling 1260 fits
0.9634615384615384
{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}


In [32]:
y_pred=svm_grid.best_estimator_.predict(X)
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

[[200   0]
 [  0 320]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       320

    accuracy                           1.00       520
   macro avg       1.00      1.00      1.00       520
weighted avg       1.00      1.00      1.00       520



In [33]:
NB_grid=GridSearchCV(GaussianNB(),{
    #'clf__priors': [None],
    'var_smoothing': [1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08,1e-9]
    
},cv=10,verbose=2,n_jobs=4,return_train_score=False)
NB_grid.fit(X, y)
print(NB_grid.best_score_)
print(NB_grid.best_params_)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
0.8807692307692309
{'var_smoothing': 0.0001}


In [34]:
y_pred=NB_grid.best_estimator_.predict(X)
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

[[176  24]
 [ 29 291]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87       200
           1       0.92      0.91      0.92       320

    accuracy                           0.90       520
   macro avg       0.89      0.89      0.89       520
weighted avg       0.90      0.90      0.90       520



In [35]:
DT_grid=GridSearchCV(DecisionTreeClassifier(),{
    'criterion':['gini','entropy'], 
    'splitter':['best','random'],
    'max_depth':[1,5,10,30], 
    'min_samples_split':[2,4,5,8,10,15,20,25,29],
    'min_samples_leaf':[1],
    #'min_weight_fraction_leaf':0.0,
    'max_features':['auto','sqrt','log2',None], 
    #'random_state':[42,None],
    #'max_leaf_nodes':None, 
    #'min_impurity_decrease':0.0, 
    #'class_weight':None, 
    #'ccp_alpha':0.0
},cv=10,verbose=2,n_jobs=4,return_train_score=False)
DT_grid.fit(X, y)
print(DT_grid.best_score_)
print(DT_grid.best_params_)

Fitting 10 folds for each of 576 candidates, totalling 5760 fits
0.9807692307692306
{'criterion': 'gini', 'max_depth': 30, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}


In [36]:
y_pred=DT_grid.best_estimator_.predict(X)
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

[[200   0]
 [  0 320]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       320

    accuracy                           1.00       520
   macro avg       1.00      1.00      1.00       520
weighted avg       1.00      1.00      1.00       520



In [37]:
knn_grid=GridSearchCV(KNeighborsClassifier(),{
    'n_neighbors':[3,5,7,9], 
    'weights':['uniform','distance'], 
    'algorithm':['auto','ball_tree', 'kd_tree','brute'], 
    'leaf_size':[2,4,8,15,20,30,35,40,50], 
    'p':[1,2,4], 
    'metric':['minkowski'],
    #'metric_params':['dict',None],
    #'n_jobs':[None]
},cv=10,verbose=2,n_jobs=4,return_train_score=False)
knn_grid.fit(X, y)
print(knn_grid.best_score_)
print(knn_grid.best_params_)

Fitting 10 folds for each of 864 candidates, totalling 8640 fits
0.946153846153846
{'algorithm': 'ball_tree', 'leaf_size': 2, 'metric': 'minkowski', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}


In [38]:
y_pred=knn_grid.best_estimator_.predict(X)
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

[[200   0]
 [  0 320]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       320

    accuracy                           1.00       520
   macro avg       1.00      1.00      1.00       520
weighted avg       1.00      1.00      1.00       520



In [39]:
LR_grid=GridSearchCV(LogisticRegression(solver='lbfgs', max_iter=400),{
    #'solver':['lbfgs'],
    #'max_iter':[400],
    'dual':[False], 
    'penalty':['l2'],
    'tol':[0.0001],
    'C':[0.1,1.0,1.5,2.0,10.0,15.0,20.0], 
    #'fit_intercept':[True], 
    #'intercept_scaling':[1], 
    'class_weight':['dict','balanced',None], 
    #'random_state':[20,42,50,None],  
    #'multi_class':['auto'], 
    #'verbose':[0], 
    #'warm_start':[False],  
    #'l1_ratio':[None]
},cv=10,verbose=2,n_jobs=4,return_train_score=False)
LR_grid.fit(X, y)
print(LR_grid.best_score_)
print(LR_grid.best_params_)

Fitting 10 folds for each of 21 candidates, totalling 210 fits
0.9307692307692307
{'C': 1.0, 'class_weight': 'dict', 'dual': False, 'penalty': 'l2', 'tol': 0.0001}


In [40]:
y_pred=LR_grid.best_estimator_.predict(X)
print(confusion_matrix(y,y_pred))
print(classification_report(y,y_pred))

[[183  17]
 [ 19 301]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.91       200
           1       0.95      0.94      0.94       320

    accuracy                           0.93       520
   macro avg       0.93      0.93      0.93       520
weighted avg       0.93      0.93      0.93       520

